apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-dockerconfig
spec:
  resources:
    inputs:
      - name: source
        type: git
      - name: image
        type: image
  params:
    - name: image-name
      description: The Name of the Image we want to use
      type: string
      default: "monkey-app"
  steps:
    - name: createConfig
      image: registry.redhat.io/ubi8/ubi-minimal
      workingDir: /opt/auths/
      command: ["/bin/bash" ,"-c"]
      args:
        - |-
          REG_SECRET=`echo -n 'myuser:mypassword' | base64 -w0`
          MY_REGISTRY="registry:5000"
          echo '{ "auths": {}}' | \
          jq '.auths += {"MY_REGISTRY": {"auth": "REG_SECRET","email": "me@working.me"}}' | \
          sed "s/REG_SECRET/$REG_SECRET/" | sed "s/MY_REGISTRY/$MY_REGISTRY/" | jq . > auth.json
  workspaces:
  - name: pipeline-ws2
    description: the locataion of the docker/config.json files
    mountPath: /opt/auths/