apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: monkey-push-task-ws
spec:
  resources:
    inputs:
      - name: source
        type: git
      - name: image
        type: image
  params:
    - name: image-name
      description: The Name of the Image we want to use
      type: string
      default: "monkey-app"
  steps:
    - name: build
      image: quay.io/buildah/stable:v1.11.0
      workingDir: /workspace/source/
      command: ["/bin/bash" ,"-c"]
      args:
        - |-
          buildah push --authfile /opt/auths/auth.json $(resources.inputs.image.name)
##################### Workspace Definition ##################
  workspaces:
  - name: pipeline-ws1
    description: the location of the containers files
    mountPath: /var/lib/containers
  - name: pipeline-ws2
    description: the locataion of the docker/config.json files
    mountPath: /opt/auths/