apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: monkey-build-task
spec:
##################### New content ###################
  resources:
    inputs:
      - {type: git, name: source}
    outputs:
      - {type: image , name: image}
##################### New content ###################
  params:
    - name: image-name
      description: The Name of the Image we want to use
      type: string
      default: "monkey-app"
  steps:
##################### New content ###################
    - name: build
      image: quay.io/buildah/stable:v1.11.0
      workingDir: /workspace/source/
      volumeMounts:
      - name: varlibcontainers
        mountPath: /var/lib/containers
      command: ["/bin/bash" ,"-c"]
      args:
        - |-
          buildah bud -f Dockerfile -t $(resources.outputs.image) .
  volumes:
  - name: varlibcontainers
    persistentVolumeClaim:
      claimName: container-build
##################### New content ###################
