apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-hello-world
spec:
  steps:
    - name: echo
      image: registry.redhat.io/ubi8/ubi-minimal
      # image: docker.io/library/ubuntu - less preferred
      command:
        - echo
      args:
        - "Hello World"
