
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: echo-hello-person
spec:
  inputs:
    params:
      - name: person
        description: Person to greet
        default: foo
  steps:
    - name: echo
      #image: registry.redhat.io/ubi8/ubi-minimal - I recommend using this image
      image: docker.io/library/ubuntu
      command:
        - echo
      args:
        - "Hello $(inputs.params.person)"
