apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: echo-hello-person-task-run-override
spec:
  taskRef:
    name: echo-hello-person
  inputs:
    params:
      - name: person
        value: bar
