apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: monkey-build-task-ws
spec:
  resources:
    inputs:
      - name: source
        type: git
      - name: image
        type: image
  params:
    - name: image-name
      description: The Name of the Image we want to use
      type: string
      default: "monkey-app"
  steps:
    - name: build
      image: quay.io/buildah/stable:v1.11.0
      workingDir: /workspace/source/
      command: ["/bin/bash" ,"-c"]
      args:
        - |-
          buildah bud --storage-driver vfs -f Dockerfile -t $(resources.inputs.image.name) .
##################### Workspace Definition ##################
  workspaces:
  - name: pipeline-ws1
    description: the location of the docker/config.json file
    mountPath: /var/lib/containers
