apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-build-push-monkey-ws
spec:
  workspaces:
    - name: pipeline-ws1
    - name: pipeline-ws2
  resources:
  - name: source
    type: git
  - name: image
    type: image
  tasks:
  - name: hello-world
    taskRef:
      name: echo-hello-world
  - name: generate-dockerconfig
    taskRef:
      name: generate-dockerconfig
    workspaces:
    - name: pipeline-ws2
      workspace: pipeline-ws2
  - name: monkey-build-task
    taskRef:
      name: monkey-build-task-ws
    runAfter: 
      - hello-world
    workspaces:
    - name: pipeline-ws1
      workspace: pipeline-ws1
    resources:
      inputs:
      - name: source
        resource: source
      - name: image
        resource: image
  - name: monkey-push-task
    taskRef:
      name: monkey-push-task-ws
    runAfter: 
      - monkey-build-task
      - generate-dockerconfig
    workspaces:
    - name: pipeline-ws1
      workspace: pipeline-ws1
    - name: pipeline-ws2
      workspace: pipeline-ws2
    resources:
      inputs:
      - name: source
        resource: source
      - name: image
        resource: image
  - name: hello-person
    taskRef:
      name: echo-hello-person
    runAfter: 
      - monkey-build-task
