kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: container-build
  namespace: ns-user01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
