kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pipeline-workspace-pvc
  namespace: ns-user01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
