kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pipeline-ws-pvc-2
  namespace: ns-user01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
