apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
##################### the pipeline information ###################
  name: build-monkey
spec:
  resources:
##################### the pipeline resource definition ###################
  - name: source
    type: git
  - name: image
    type: image
  tasks:
##################### the tasks reference ###################
  - name: hello-world
    taskRef:
      name: echo-hello-world
  - name: monkey-build-task
    taskRef:
      name: monkey-build-task
    runAfter: 
      - hello-world
    resources:
      inputs:
      - name: source
        resource: source
      outputs:
      - name: image
        resource: image
  - name: hello-person
    taskRef:
      name: echo-hello-person
    runAfter:
      - monkey-build-task
